resources:
  - mongo-config.yaml
  - mongo-secret.yaml
  - mongo.yaml
  - webapp.yaml

labels:
  - pairs:
      app: webapp

namePrefix: kustom-

nameSuffix: -v1

configMapGenerator:
- name: mykustom-map