apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   argocd.argoproj.io/tracking-id: kustom-dev:/Service:dev/kustom-webapp-service-v1
  labels:
    app: webapp-service
  name: kustom-webapp-service-v1
 
spec:
  ports:
    - nodePort: 30100
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort